# Generated by Django 2.0 on 2018-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='constant_key')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='constant_value')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '常量管理',
                'verbose_name_plural': '常量管理',
                'db_table': 'ys_constant',
            },
        ),
    ]
