# Generated by Django 2.0 on 2019-01-17 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_info', models.TextField(verbose_name='消息')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('flag', models.IntegerField(default=0, verbose_name='标签')),
            ],
            options={
                'verbose_name': '系统消息',
                'verbose_name_plural': '系统消息',
                'db_table': 'system_message',
            },
        ),
    ]
