# Generated by Django 2.0 on 2018-10-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YiShengUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司名')),
            ],
            options={
                'verbose_name': '易数宝用户',
                'verbose_name_plural': '易数宝用户',
                'db_table': 'yisheng_user',
            },
        ),
    ]
