# Generated by Django 2.0 on 2018-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField(default=False, verbose_name='是否根部门')),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
                ('parentId', models.IntegerField(blank=True, default=None, null=True, verbose_name='上级部门')),
                ('departCode', models.CharField(max_length=255, unique=True, verbose_name='部门编码')),
            ],
            options={
                'verbose_name': '部门管理',
                'verbose_name_plural': '部门管理',
                'db_table': 'ys_depart',
            },
        ),
    ]
